-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "wines" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "wines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"uuid" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"type" varchar DEFAULT '',
	"vintage" varchar DEFAULT '',
	"country" varchar DEFAULT '',
	"name" varchar DEFAULT '',
	"producer" varchar DEFAULT '',
	"appelation" varchar DEFAULT '',
	"price" json
);

*/